# Configuration file for the plugin. You can change the values as needed.
# Change either through the in-game commands/menus or by editing this file directly.

# Whether the plugin is enabled or not.
# Default value: true
enabled: true

# Language setting for the plugin's messages.
# Supported languages: en (English), de (German)
# Default value: en
language: en

# Whether to only allow the plugin's features when using an axe.
# If false, bare hand may also trigger the tree destruction.
# Default value: true
onlyAxe: true

# Whether to only allow the plugin's features only in survival mode.
# If true, players not in survival mode will not be affected by the plugin.
# default value: true
onlySurvival: true

# The speed at which the logs will be destroyed.
# Value range: 0 (depending on tool), 1 (fastest) to 5 (slowest).
# Default value: 3
speed: 3

# The maximum number of logs that can be destroyed in one tree.
# Do not set this value too high, as it may cause performance issues on larger trees.
# NOT RECOMMENDED: Setting value to 0 results in no limit.
# Default value: 64
limit: 64

# Check if it's a tree before destroying the logs.
treeDetection:
  # Whether to enable tree detection or not.
  # Default value: false
  enabled: false
  # Sets the mode of the check.
  # Value range: 1 (leaf check), 2 (CoreProtect check)
  # Note: Tree detection with CoreProtect only works on natural trees. Self-grown trees won't trigger plugin.
  # default value: 1
  mode: 1
  # Whether to check every log or only the first one.
  # Default value: true
  deep: true
